### PR TITLE
fixed flash message layout

### PR DESCRIPTION
**Pull request by eshaiju**
Before Fix:
27144325-ffb6625e-514e-11e7-8cbf-db04190d69aa

After Fix:
screen shot 2017-06-18 at 1 46 44 am

@ayann

### CODE REVIEW

**Comment by Martin288** [comment]
@eshaiju thanks for your work. But I think it'd better to adjust flashes style to match the theme. I added these codes in my own application:
```scss
.flashes {
  width: 84.1%;
  float: right;
}

body.logged_in .flashes .flash {
  background-image: none;
  border-bottom: none;
  font-weight: normal;
  color: white;

  &.flash_notice {
    background: $skinActiveColor;
  }
  &.flash_error {
    background: #FF6C60;   /* background same to delete button in this theme */
  }
  &.flash_alert {
    background: #BDB446;
  }
}
```
And I get the below result:
image

**Comment by eshaiju** [comment]
👍

**Comment by gerryhd** [comment]
This seems to still be present in the current version despite the fix

image

**Comment by Nikitakan** [comment]
great it helps me, Thank you.

**Pull request merged**
